const statistic = [
  {
    id: 1,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Наличка",
    numberProduct: 1,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "сапборд",
  },
  {
    id: 2,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Наличка",
    numberProduct: 2,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "сапборд",
  },
  {
    id: 3,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Паспорт",
    numberProduct: 3,
    timeRental: 0.5,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "сапборд",
  },
  {
    id: 4,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Наличка",
    numberProduct: 6,
    timeRental: 0.5,
    date: "10.09.2022 05:10",
    status: "Завершённый",
    product: "сапборд",
  },
  {
    id: 5,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 1,
    timeRental: 0.5,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "сапборд",
  },
  {
    id: 6,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 1,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Завершённый",
    product: "сапборд",
  },
  {
    id: 7,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Паспорт",
    numberProduct: 1,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "сапборд",
  },
  {
    id: 8,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 1,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "сапборд",
  },
  {
    id: 9,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 3,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "велосипед",
  },
  {
    id: 10,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Наличка",
    numberProduct: 2,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "велосипед",
  },
  {
    id: 11,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 3,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Завершённый",
    product: "велосипед",
  },
  {
    id: 12,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 2,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "велосипед",
  },
  {
    id: 13,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Паспорт",
    numberProduct: 2,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "велосипед",
  },
  {
    id: 14,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Наличка",
    numberProduct: 4,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Завершённый",
    product: "велосипед",
  },
  {
    id: 15,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Наличка",
    numberProduct: 1,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Завершённый",
    product: "велосипед",
  },
  {
    id: 16,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 2,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "велосипед",
  },
  {
    id: 17,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Паспорт",
    numberProduct: 2,
    timeRental: 12,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "велосипед",
  },
  {
    id: 18,
    telephone: 83427582419,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Наличка",
    numberProduct: 2,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "сапборд",
  },
  {
    id: 19,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Наличка",
    numberProduct: 2,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "сапборд",
  },
  {
    id: 20,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Паспорт",
    numberProduct: 2,
    timeRental: 1.5,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "сапборд",
  },
  {
    id: 21,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Наличка",
    numberProduct: 1,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Завершённый",
    product: "сапборд",
  },
  {
    id: 22,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 1,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "сапборд",
  },
  {
    id: 23,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 2,
    timeRental: 0.5,
    date: "10.09.2022 05:10",
    status: "Завершённый",
    product: "сапборд",
  },
  {
    id: 24,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Паспорт",
    numberProduct: 2,
    timeRental: 0.5,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "сапборд",
  },
  {
    id: 25,
    telephone: 1221413535,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 3,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "сапборд",
  },
  {
    id: 26,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 2,
    timeRental: 1.5,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "велосипед",
  },
  {
    id: 27,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Паспорт",
    numberProduct: 1,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "велосипед",
  },
  {
    id: 28,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 1,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Завершённый",
    product: "велосипед",
  },
  {
    id: 29,
    telephone: 111111111,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 1,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "велосипед",
  },
  {
    id: 30,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Паспорт",
    numberProduct: 1,
    timeRental: 12,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "велосипед",
  },
  {
    id: 31,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Наличка",
    numberProduct: 1,
    timeRental: 24,
    date: "10.09.2022 05:10",
    status: "Завершённый",
    product: "велосипед",
  },
  {
    id: 32,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Наличка",
    numberProduct: 1,
    timeRental: 24,
    date: "10.09.2022 05:10",
    status: "Завершённый",
    product: "велосипед",
  },
  {
    id: 33,
    telephone: 8927494083,
    name: "Семин Андрей Валерьевич",
    payment: "Перевод",
    deposit: "Паспорт",
    numberProduct: 2,
    timeRental: 24,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "велосипед",
  },
  {
    id: 34,
    telephone: 8927446346343,
    name: "Семин Андрей Валерьевич",
    payment: "Наличка",
    deposit: "Паспорт",
    numberProduct: 1,
    timeRental: 1,
    date: "10.09.2022 05:10",
    status: "Активный",
    product: "велосипед",
  },
];

if (!localStorage.getItem("statistic")) {
  localStorage.setItem("statistic", JSON.stringify(statistic));
}
const fetchAll = () =>
  new Promise((resolve) => {
    window.setTimeout(function () {
      resolve(JSON.parse(localStorage.getItem("statistic")));
    }, 2000);
  });
export default {
  fetchAll,
};
